spring:
  config:
    activate:
      on-profile: dev

logging:
  datasource:
    show-sql: ${SHOW_SQL:false}
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:info}
    'com.prosperapagamentos': ${DEFAULT_LOG_LEVEL:debug}
